services:
  algebra.webshop2025.app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - SQL_CONNECTIONSTRING=Server=sqlserver;Database=WebShopDB;User Id=sa;Password=YourStrongPassw0rd;Encrypt=False;TrustServerCertificate=True;
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  sqlserver:
    environment:
      - ACCEPT_EULA="Y"
      - SA_PASSWORD="YourStrongPassw0rd"
    ports:
      - "1434:1433"